# Dockerfile used to build video software stack
#
# Copyright 2022, Advanced Micro Device, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM ubuntu:22.04
WORKDIR /usr/src/build

# This is necessary to avoid using /bin/sh by default
SHELL ["/bin/bash", "-c"]

# Install git and other dependencies not covered by xrtdeps.sh
RUN export DEBIAN_FRONTENT=noninteractive && \
    ln -sf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && \
    apt-get update && \
    apt-get install -y \
    tzdata \
    sudo \
    git \
    python3

RUN git clone https://github.com/gdraheim/docker-systemctl-replacement.git /usr/local/share/docker-systemctl-replacement && \
    echo "alias systemctl='python3 /usr/local/share/docker-systemctl-replacement/files/docker/systemctl3.py'" >> /root/.bashrc && \
    ln -s /usr/local/share/docker-systemctl-replacement/files/docker/systemctl3.py /usr/local/bin/systemctl

# Dockerfile assumes that the video-sdk repo has been cloned locally
COPY release/U30_Ubuntu_22.04_v3.0/ ./release/U30_Ubuntu_22.04_v3.0/
RUN cd /usr/src/build/release/U30_Ubuntu_22.04_v3.0; ./install -f
